const mongoose = require("mongoose");
require("dotenv").config();

const Job = require("./models/Job");
const Company = require("./models/Company");

async function seedJobs() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to DB");

    await Job.deleteMany();
    await Company.deleteMany();

    const companies = await Company.insertMany([
      { companyName: "TechNova", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "Capital Insights", companyLocation: "Troy, NY", companyWebsite: "https://example.com" },
      { companyName: "Hudson Digital", companyLocation: "Schenectady, NY", companyWebsite: "https://example.com" },
      { companyName: "Empire Systems", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "SecureNY", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "Albany Tech Hub", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "AI Labs NY", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "QualityWorks", companyLocation: "Colonie, NY", companyWebsite: "https://example.com" },
      { companyName: "EduBridge", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
      { companyName: "HealthData NY", companyLocation: "Albany, NY", companyWebsite: "https://example.com" },
    ]);

    const c = {};
    companies.forEach((company) => {
      c[company.companyName] = company._id;
    });

    const jobs = [
      {
        jobTitle: "Software Engineer Intern",
        companyName: "TechNova",
        companyId: c["TechNova"],
        address: "Downtown Albany, NY",
        employmentType: "Internship Hybrid",
        salaryRange: "$25/hr",
        jobDescription: "Work on frontend and backend features using React, Node.js, and MongoDB.",
        applicationLink: "https://example.com/apply/software-engineer-intern",
        applicationDeadlineDate: new Date("2026-06-01"),
        latitude: 42.6526,
        longitude: -73.7562,
      },
      {
        jobTitle: "Data Analyst",
        companyName: "Capital Insights",
        companyId: c["Capital Insights"],
        address: "Troy, NY",
        employmentType: "Full-time On-site",
        salaryRange: "$68K - $82K",
        jobDescription: "Analyze datasets, build dashboards, and write SQL queries for business reports.",
        applicationLink: "https://example.com/apply/data-analyst",
        applicationDeadlineDate: new Date("2026-05-20"),
        latitude: 42.7284,
        longitude: -73.6918,
      },
      {
        jobTitle: "Frontend Developer",
        companyName: "Hudson Digital",
        companyId: c["Hudson Digital"],
        address: "Schenectady, NY",
        employmentType: "Full-time Hybrid",
        salaryRange: "$70K - $90K",
        jobDescription: "Build responsive user interfaces using React, CSS, and JavaScript.",
        applicationLink: "https://example.com/apply/frontend-developer",
        applicationDeadlineDate: new Date("2026-05-15"),
        latitude: 42.8142,
        longitude: -73.9396,
      },
      {
        jobTitle: "Backend Developer Intern",
        companyName: "Empire Systems",
        companyId: c["Empire Systems"],
        address: "Albany, NY",
        employmentType: "Internship On-site",
        salaryRange: "$22/hr",
        jobDescription: "Develop REST API endpoints using Node.js, Express, and MongoDB.",
        applicationLink: "https://example.com/apply/backend-intern",
        applicationDeadlineDate: new Date("2026-06-10"),
        latitude: 42.6600,
        longitude: -73.7500,
      },
      {
        jobTitle: "Cybersecurity Analyst",
        companyName: "SecureNY",
        companyId: c["SecureNY"],
        address: "Albany, NY",
        employmentType: "Full-time Remote",
        salaryRange: "$75K - $95K",
        jobDescription: "Monitor security alerts, review logs, and support vulnerability management.",
        applicationLink: "https://example.com/apply/cybersecurity-analyst",
        applicationDeadlineDate: new Date("2026-05-25"),
        latitude: 42.6500,
        longitude: -73.7700,
      },
      {
        jobTitle: "IT Support Specialist",
        companyName: "Albany Tech Hub",
        companyId: c["Albany Tech Hub"],
        address: "Albany, NY",
        employmentType: "Part-time On-site",
        salaryRange: "$20/hr",
        jobDescription: "Help users troubleshoot hardware, software, accounts, and network issues.",
        applicationLink: "https://example.com/apply/it-support",
        applicationDeadlineDate: new Date("2026-05-30"),
        latitude: 42.6400,
        longitude: -73.7400,
      },
      {
        jobTitle: "Machine Learning Intern",
        companyName: "AI Labs NY",
        companyId: c["AI Labs NY"],
        address: "Albany, NY",
        employmentType: "Internship Remote",
        salaryRange: "$28/hr",
        jobDescription: "Assist with machine learning experiments, data preprocessing, and model evaluation.",
        applicationLink: "https://example.com/apply/ml-intern",
        applicationDeadlineDate: new Date("2026-06-05"),
        latitude: 42.6700,
        longitude: -73.7600,
      },
      {
        jobTitle: "QA Tester",
        companyName: "QualityWorks",
        companyId: c["QualityWorks"],
        address: "Colonie, NY",
        employmentType: "Full-time Hybrid",
        salaryRange: "$60K - $75K",
        jobDescription: "Test web applications, write bug reports, and perform regression testing.",
        applicationLink: "https://example.com/apply/qa-tester",
        applicationDeadlineDate: new Date("2026-05-18"),
        latitude: 42.7200,
        longitude: -73.8200,
      },
      {
        jobTitle: "Teacher Assistant",
        companyName: "EduBridge",
        companyId: c["EduBridge"],
        address: "Albany, NY",
        employmentType: "Part-time On-site",
        salaryRange: "$18/hr",
        jobDescription: "Support classroom activities, help students, and assist with lesson materials.",
        applicationLink: "https://example.com/apply/teacher-assistant",
        applicationDeadlineDate: new Date("2026-05-12"),
        latitude: 42.6510,
        longitude: -73.7550,
      },
      {
        jobTitle: "Software Developer",
        companyName: "Empire Systems",
        companyId: c["Empire Systems"],
        address: "Latham, NY",
        employmentType: "Full-time Remote",
        salaryRange: "$85K - $110K",
        jobDescription: "Build and maintain internal software systems using JavaScript and cloud tools.",
        applicationLink: "https://example.com/apply/software-developer",
        applicationDeadlineDate: new Date("2026-06-15"),
        latitude: 42.7460,
        longitude: -73.7600,
      },
      {
        jobTitle: "Database Intern",
        companyName: "HealthData NY",
        companyId: c["HealthData NY"],
        address: "Albany, NY",
        employmentType: "Internship Hybrid",
        salaryRange: "$24/hr",
        jobDescription: "Assist with database cleanup, SQL reports, and data validation tasks.",
        applicationLink: "https://example.com/apply/database-intern",
        applicationDeadlineDate: new Date("2026-05-09"),
        latitude: 42.6550,
        longitude: -73.7600,
      },
      {
        jobTitle: "Business Analyst",
        companyName: "Capital Insights",
        companyId: c["Capital Insights"],
        address: "Albany, NY",
        employmentType: "Full-time Hybrid",
        salaryRange: "$65K - $85K",
        jobDescription: "Gather requirements, document workflows, and support product planning.",
        applicationLink: "https://example.com/apply/business-analyst",
        applicationDeadlineDate: new Date("2026-06-20"),
        latitude: 42.6605,
        longitude: -73.7580,
      },
      {
        jobTitle: "Web Developer Intern",
        companyName: "Hudson Digital",
        companyId: c["Hudson Digital"],
        address: "Albany, NY",
        employmentType: "Internship Remote",
        salaryRange: "$21/hr",
        jobDescription: "Create web pages, fix UI bugs, and support React components.",
        applicationLink: "https://example.com/apply/web-dev-intern",
        applicationDeadlineDate: new Date("2026-05-28"),
        latitude: 42.6460,
        longitude: -73.7605,
      },
      {
        jobTitle: "Network Technician",
        companyName: "Albany Tech Hub",
        companyId: c["Albany Tech Hub"],
        address: "Guilderland, NY",
        employmentType: "Full-time On-site",
        salaryRange: "$55K - $70K",
        jobDescription: "Install, configure, and troubleshoot network equipment and user connectivity.",
        applicationLink: "https://example.com/apply/network-technician",
        applicationDeadlineDate: new Date("2026-05-22"),
        latitude: 42.7048,
        longitude: -73.9115,
      },
      {
        jobTitle: "Security Engineering Intern",
        companyName: "SecureNY",
        companyId: c["SecureNY"],
        address: "Albany, NY",
        employmentType: "Internship Hybrid",
        salaryRange: "$26/hr",
        jobDescription: "Support security automation, alert triage, and internal security tooling.",
        applicationLink: "https://example.com/apply/security-engineering-intern",
        applicationDeadlineDate: new Date("2026-06-02"),
        latitude: 42.6490,
        longitude: -73.7610,
      },
      {
        jobTitle: "AI Research Assistant",
        companyName: "AI Labs NY",
        companyId: c["AI Labs NY"],
        address: "Rensselaer, NY",
        employmentType: "Part-time Remote",
        salaryRange: "$23/hr",
        jobDescription: "Help evaluate AI models, collect datasets, and document experiment results.",
        applicationLink: "https://example.com/apply/ai-research-assistant",
        applicationDeadlineDate: new Date("2026-05-14"),
        latitude: 42.6426,
        longitude: -73.7429,
      },
      {
        jobTitle: "Product Management Intern",
        companyName: "TechNova",
        companyId: c["TechNova"],
        address: "Albany, NY",
        employmentType: "Internship Hybrid",
        salaryRange: "$22/hr",
        jobDescription: "Assist with product research, feature planning, and user feedback summaries.",
        applicationLink: "https://example.com/apply/product-management-intern",
        applicationDeadlineDate: new Date("2026-06-12"),
        latitude: 42.6542,
        longitude: -73.7544,
      },
      {
        jobTitle: "Help Desk Technician",
        companyName: "HealthData NY",
        companyId: c["HealthData NY"],
        address: "Albany, NY",
        employmentType: "Part-time On-site",
        salaryRange: "$19/hr",
        jobDescription: "Respond to support tickets, reset accounts, and troubleshoot user issues.",
        applicationLink: "https://example.com/apply/help-desk",
        applicationDeadlineDate: new Date("2026-05-11"),
        latitude: 42.6535,
        longitude: -73.7577,
      },
      {
        jobTitle: "Cloud Engineer",
        companyName: "Empire Systems",
        companyId: c["Empire Systems"],
        address: "Albany, NY",
        employmentType: "Full-time Remote",
        salaryRange: "$95K - $120K",
        jobDescription: "Support cloud deployments, monitoring, automation, and infrastructure scripting.",
        applicationLink: "https://example.com/apply/cloud-engineer",
        applicationDeadlineDate: new Date("2026-06-25"),
        latitude: 42.6610,
        longitude: -73.7650,
      },
      {
        jobTitle: "UX Designer Intern",
        companyName: "Hudson Digital",
        companyId: c["Hudson Digital"],
        address: "Schenectady, NY",
        employmentType: "Internship Hybrid",
        salaryRange: "$20/hr",
        jobDescription: "Create wireframes, improve user flows, and assist with usability testing.",
        applicationLink: "https://example.com/apply/ux-designer-intern",
        applicationDeadlineDate: new Date("2026-05-26"),
        latitude: 42.8120,
        longitude: -73.9400,
      },
    ];

    await Job.insertMany(jobs);

    console.log(`${jobs.length} jobs seeded successfully`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedJobs();